name: GSI Build

on: [push]

env:
  ROM_NAME: AOSP
  ZIP_NAME: AOSP
  TZ: Europe/London
  MIR: gof
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master

       - name: Initializing telegram bot
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}

         run: |
              sudo install telegram /usr/bin
              chmod +x build/initial.sh
              . build/initial.sh

       - name: Install platform-tools
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}

         run: |
              telegram -M -C "`printenv ROM_NAME` - Installing platform-tools"
              wget "https://dl.google.com/android/repository/platform-tools-latest-linux.zip"
              mkdir -p ~/.local/bin
              unzip platform-tools-latest-linux.zip -d ~/.local/bin
              source ~/.profile

       - name: Install build dependencies
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}

         run: |
              telegram -M -C "`printenv ROM_NAME` - Installing build dependencies"
              sudo apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev git-repo
              sudo snap install git-repo

       - name: Execute Shell Script
         env:
              TOKEN: ${{ secrets.BOT_TOKEN }}
              
         run: |
               chmod +x build/build.sh
               . build/build.sh

       - name: Send build info to Telegram
         env:
              CHAT_ID: ${{ secrets.CHAT_ID }}
              BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
              API_ID: ${{ secrets.API_ID }}
              API_HASH: ${{ secrets.API_HASH }}
         run: |
              python .github/workflows/robot.py
